<?php
$this->headLink()->appendStylesheet($this->basePath('css/pages/index.css'))
    ->appendStylesheet($this->basePath('css/utilidades/alerts.css'))
    ->appendStylesheet($this->basePath('css/utilidades/tabela.css'));

$this->headScript()->appendFile($this->basePath('/js/gestao-frota/veiculo/index.js'));
?>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
<section class="menu">
    <div class="container">
        <div class="opcoes">
            <h1>Gestão dos Veículos</h1>
            <table class="styled-table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Modelo</th>
                    <th>Marca</th>
                    <th>Ano</th>
                    <th>Cor</th>
                    <th>Placa</th>
                    <th>Renavam</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->veiculos as $veiculo): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($veiculo['id_veiculo']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['modelo']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['marca']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['ano']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['cor']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['placa']); ?></td>
                        <td><?php echo htmlspecialchars($veiculo['renavam']); ?></td>
                        <td>
                            <a href="#" id="editaVeiculo" class="btn-edit">Editar</a>
                            <a href="#" id="deletaVeiculo" class="btn-delete">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <a href="#" id="novoVeiculo" class="remov-link button-motoristas w-button modal-veiculo">Novo Veículo</a>
            <a href="<?php echo $this->basePath('home'); ?>" class="remov-link button-veiculos w-button">Voltar</a>
        </div>
    </div>
    <div>
        <div id="success-alert"></div>
        <div id="error-alert"></div>
    </div>
    <div>
        <?php include 'modal-cadastro-veiculo.phtml'; ?>
        <?php include 'modal-edita-veiculo.phtml'; ?>
        <?php include 'modal-exclui-veiculo.phtml'; ?>
    </div>
    <div id="modalVeiculo" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <div id="modalContent"></div>
        </div>
    </div>
    <div id="modalEditaVeiculo" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <div id="modalContent"></div>
        </div>
    </div>
    <div id="modalExcluiVeiculo" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <div id="modalContent"></div>
        </div>
    </div>
</section>
</body>
</html>