version: '3.8'

services:
  app:
    image: php:7.4-apache
    container_name: php-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]

  composer:
    image: composer:2.7.1
    container_name: composer-container
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    working_dir: /var/www/html
    command: ["install"]  # ou ["update"]

  node:
    image: node:14  # ou qualquer versão mais recente do Node
    container_name: node-container
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules  # Para garantir que os node_modules não sejam sobrescritos
    working_dir: /var/www/html
    command: ["npm", "install"]
