<?php
    $this->headLink()->appendStylesheet($this->basePath('css/utilidades/modal.css'));
    $this->headLink()->appendStylesheet($this->basePath('css/pages/modal-exclui-motorista.css'));

    $this->headScript()->appendFile($this->basePath('/js/gestao-frota/motorista/modal-exclui-motorista.js'));
?>

<div id="modalExcluiMotorista" class="modal" style="display: none;">
    <div class="modal-content">
        <span id="closerModalExclui" class="close-btn">&times;</span>
        <h2>Excluir motorista</h2>
        <p class="highlight-message">Antes de realizar a exclução, realize a verificação dos dados a baixo</p>
        <form id="formExcluiMotorista">
            <input type="hidden" id="id" name="id">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" name="nome" id="nome" disabled>
            </div>
            <div class="form-group">
                <label for="rg">RG:</label>
                <input type="text" name="rg" id="rg" disabled>
            </div>
            <div class="form-group">
                <label for="cpf">CPF:</label>
                <input type="text" id="cpf" name="cpf" disabled="disabled">
            </div>
            <div class="form-group">
                <label for="telefone">Telefone:</label>
                <input type="text" id="telefone" name="telefone" disabled>
            </div>
            <div class="form-group">
                <label for="placaVeiculo">Placa do Veiculo:</label>
                <input type="text" id="placaVeiculo" name="placaVeiculo" disabled>
            </div>
            <button type="submit" class="btn-excluir">Excluir</button>
        </form>
    </div>
</div>