<?php
    $this->headLink()->appendStylesheet($this->basePath('css/utilidades/modal.css'));

    $this->headScript()->appendFile($this->basePath('/js/gestao-frota/motorista/modal-edita-motorista.js'));
?>

<div id="modalEditaMotorista" class="modal" style="display: none;">
    <div class="modal-content">
        <span id="closerModal" class="close-btn">&times;</span>
        <h2>Editar motorista</h2>
        <form id="formEditaMotorista">
            <input type="hidden" id="id" name="id">
            <div class="form-group">
                <label for="nome">Nome: *</label>
                <input type="text" name="nome" id="nome" required>
            </div>
            <div class="form-group">
                <label for="rg">RG: *</label>
                <input type="text" name="rg" id="rg" required>
            </div>
            <div class="form-group">
                <label for="cpf">CPF:</label>
                <input type="text" id="cpf" name="cpf" disabled="disabled">
            </div>
            <div class="form-group">
                <label for="telefone">Telefone:</label>
                <input type="text" id="telefone" name="telefone">
            </div>
            <div class="form-group">
                <label for="placaVeiculo">Placa do Veiculo:</label>
                <input type="text" id="placaVeiculo" name="placaVeiculo">
            </div>
            <button type="submit" class="submit-btn">Salvar</button>
        </form>
    </div>
</div>