<?php
    $this->headLink()->appendStylesheet($this->basePath('css/utilidades/modal.css'));
?>

<div id="modalMotorista" class="modal" style="display: none;">
    <div class="modal-content">
        <span id="closeModal" class="close-btn">&times;</span>
        <h2>Cadastro de novo motorista</h2>
        <form id="formMotorista">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" name="nome" id="nome">
            </div>
            <div class="form-group">
                <label for="rg">RG:</label>
                <input type="text" name="rg" id="rg">
            </div>
            <div class="form-group">
                <label for="cpf">CPF:</label>
                <input type="text" id="cpf" name="cpf">
            </div>
            <div class="form-group">
                <label for="telefone">Telefone:</label>
                <input type="text" id="telefone" name="telefone">
            </div>
            <div class="form-group">
                <label for="placaVeiculo">Placa do Veiculo:</label>
                <input type="text" id="placaVeiculo" name="placaVeiculo">
            </div>
            <button type="submit" class="submit-btn">Cadastrar</button>
        </form>
    </div>
</div>