<?php
    $this->headLink()->appendStylesheet($this->basePath('css/pages/index.css'));
?>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
<div id="modalMotorista" class="modal" style="display: none;">
    <div class="modal-content">
        <h2>Gerenciamento de Motoristas</h2>

    </div>
</div>

<section class="menu">
    <div class="container">
        <div class="opcoes">
            <img class="imagem" src="<?php echo $this->basePath('/img/img_frota.png'); ?>" alt="Logo">
            <h1>Gestão da Frota</h1>
            <div id="modalMotoristas" class="modal-overlay" style="display: none;">
                <div class="modal-content">
                    <span class="close-modal">&times;</span>
                    <div id="modalContent"></div>
                </div>
            </div>
            <a href="<?php echo $this->basePath('/gestao-frota/motorista'); ?>" class="button-motoristas w-button modal-motorista">Gerenciar Motoristas</a>
            <a href="<?php echo $this->basePath('/gestao-frota/veiculo'); ?>" class="button-veiculos w-button">Gerenciar Veículos</a>
        </div>
    </div>
</section>
</body>
</html>
